// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorCredito.Infra.Persistance;

#nullable disable

namespace SimuladorCredito.Infra.Data.Migrations
{
    [DbContext(typeof(BancoLocalDbContext))]
    partial class BancoLocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("CoSimulacao")
                        .HasColumnType("int")
                        .HasColumnName("CO_SIMULACAO");

                    b.Property<int>("CoResultaSimulacao")
                        .HasColumnType("int")
                        .HasColumnName("CO_RESULTADO_SIMULACAO");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("NUMERO");

                    b.Property<decimal>("ValorAmortizacao")
                        .HasPrecision(22, 10)
                        .HasColumnType("decimal(22,10)")
                        .HasColumnName("VALOR_AMORTIZACAO");

                    b.Property<decimal>("ValorJuros")
                        .HasPrecision(22, 10)
                        .HasColumnType("decimal(22,10)")
                        .HasColumnName("VALOR_JUROS");

                    b.HasKey("CoSimulacao", "CoResultaSimulacao", "Numero");

                    b.ToTable("Parcelas", (string)null);
                });

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.ResultadoSimulacao", b =>
                {
                    b.Property<int>("CoSimulacao")
                        .HasColumnType("int")
                        .HasColumnName("CO_SIMULACAO");

                    b.Property<int>("CoResultaSimulacao")
                        .HasColumnType("int")
                        .HasColumnName("CO_RESULTADO_SIMULACAO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO");

                    b.HasKey("CoSimulacao", "CoResultaSimulacao");

                    b.ToTable("RESULTADOS_SIMULACOES", (string)null);
                });

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("CoSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_SIMULACAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoSimulacao"));

                    b.Property<int>("CoProduto")
                        .HasColumnType("int")
                        .HasColumnName("CO_PRODUTO");

                    b.Property<decimal>("PcTaxaJuros")
                        .HasPrecision(12, 8)
                        .HasColumnType("decimal(12,8)")
                        .HasColumnName("PC_TAXA_JUROS");

                    b.HasKey("CoSimulacao");

                    b.ToTable("Simulacoes", (string)null);
                });

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("SimuladorCredito.Domain.Entities.ResultadoSimulacao", "ResultadoSimulacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("CoSimulacao", "CoResultaSimulacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultadoSimulacao");
                });

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.ResultadoSimulacao", b =>
                {
                    b.HasOne("SimuladorCredito.Domain.Entities.Simulacao", "Simulacao")
                        .WithMany("ResultadosSimulacao")
                        .HasForeignKey("CoSimulacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.ResultadoSimulacao", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("SimuladorCredito.Domain.Entities.Simulacao", b =>
                {
                    b.Navigation("ResultadosSimulacao");
                });
#pragma warning restore 612, 618
        }
    }
}
