services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "passwordLocal123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulador
    depends_on:
      - sqlserver
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  sqlserver_data:
